# This file tells Railway exactly how to build and run your app.

# Explicitly request both Python and Node.js environments.
# This is the key fix for the "npm: command not found" error.
providers = ["python", "nodejs"]

# Define the build phase
[phases.build]
# This is the command to install Node modules and build your React app.
cmds = ["npm install --prefix interview-app && npm run build --prefix interview-app"]

# Define the start phase
[start]
# This is the command to run your Gunicorn server.
# This replaces the need for a Procfile.
cmd = "gunicorn PEC_app:app"
