# This file tells Railway exactly how to build and run your app.

# CORRECTED: Change "nodejs" to "node"
providers = ["python", "nodejs"]

# Define the build phase
[phases.build]
# This is the command to install Node modules and build your React app.
cmds = ["npm install --prefix interview-app && npm run build --prefix interview-app"]

# Define the start phase
[start]
# This is the command to run your Gunicorn server.
cmd = "gunicorn PEC_app:app"
